version: '3.7'
services:
    nginx:
        image: 'joebenrob/nginx:latest'
        volumes:
            - {(type: 'bind, source: ./nginx/nginx.conf, target: /etc/nginx/nginx.conf)'}
        ports:
            - {target: 80, published: 80, protocol: tcp}
        depends_on:
        - static_website
    server:
        image: 'rjharrisuk/server:latest'
        build: {context: ./server, dockerfile: Dockerfile}
        ports: [{target: 8084, protocol: tcp}]
        depends_on:
        - prize_gen
    text_gen:
        image: joebenrob/text_gen
        build: {context: ./text_gen, dockerfile: Dockerfile, args: {VERSION: text_gen_1}}
        ports: [{target: 8085, protocol: tcp}]
        depends_on:
        - server
    num_gen:
        image: joebenrob/num_gen
        build: {context: ./num_gen, dockerfile: Dockerfile, args: {VERSION: text_gen_1}}
        ports: [{target: 8086, protocol: tcp}]
        depends_on:
        - server
    prize_gen:
        image: joebenrob/prize_gen
        build: {contect: ./num_gen, dockerfile: Dockerfile, args: {VERSION: prize_gen_1}}
        depends_on:
        - db_connector
    notification_server:
        image: 'rjharrisuk/notification_server:latest'
        build: {context: ./notification_server, dockerfile: Dockerfile}
        ports: [{target: 9000, protocol: tcp}]
        depends_on:
        - prize_gen
    static_website:
        image: 'rjharrisuk/static_website:latest'
        build: {context: ./static_website, dockerfile: Dockerfile, ports: [{target: 8089, protocol: tcp}]}
        depends_on:
        - server
    db_connector:
        image: 'rjharrisuk/db_connector:latest'
        build: {context: ./db_connector, dockerfile: Dockerfile, ports: [{target: 5001, protocol: tcp}]}
        depends_on:
        - mongo
    mongo:
        image: 'mongo:latest'
        ports: [{target: 27017, protocol: tcp, published: 27017}]
