apiVersion: apps/v1
kind: Deployment
metadata:
  name: num-gen
  labels: 
    app: num_gen
spec:
  selector:
    matchLabels:
      app: num_gen
  template:
    metadata:
      labels:
        app: num_gen
    spec:
      containers:
      - name: num-gen
        image: joebenrob/num_gen:1
        ports:
        - containerPort: 8086
