version: '3.3'
services:
    static_website:
      container_name: static_website
      image: rjharrisuk/static_website
      ports:
      - target: 8089
        published: 8089
    server:
      container_name: server
      image: rjharrisuk/server
      ports:
      - target: 8084
        published: 8084
    nginx:
      container_name: nginx
      image: nginx
      volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
